import { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
  title: 'Next.js App - Blog',
  description: 'Generated by create next app',
}

const BlogLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      <p>Blog Layout</p>
      {children}
    </div>
  )
}

export default BlogLayout
